server:
  port: ${PORT:5555}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      default: dev
      dev:
        - database-dev
      stg:
        - database-stg
      prod:
        - database-prod