server:
  host: "0.0.0.0"

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      default: dev
      dev:
        - database-dev
      stg:
        - database-stg
      prod:
        - database-prod